### PR TITLE
Fix/trajectory actionlib

### PR DESCRIPTION
**Pull request by reinzor**
fix(reference_generator): Infinite while loop  …
Do not try to lower the velocity in order to reach the next subgoal,
this resulted in an infinite while loop. Just try to reacht the next
subgoal, if this cannot be done, notify the caller. I will test whether
this performs well in practice, if not, I will try a finite optimization
with a max iterations.

### CODE REVIEW

**Comment by reinzor** [comment]
We have to discuss this next Tuesday. Fixing this infinite while loop causes problems since executives are not properly waiting for goals to complete. We have to discuss the desired behavior.

**Comment by LoyVanBeek** [comment]
So, the problem is that the executives are sending goals before a previous goal has been completed/cancelled?

**Comment by reinzor** [comment]
Yes, more or less. We will discuss Tuesday.

-Rein

**Comment by reinzor** [comment]
@Timple , can you review?

**Review by Timple — APPROVED** [review]

**Pull request merged**
